title: Benjamin's Blog of Git
author: Benjamin Herfray
email: bherf1@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
  This is a completely random blog of no real purpose whatsoever. 
  So, if you would like to read random stuff of absolutely no productive 
  importance whatsoever, you are in the right place!

theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
